### PR TITLE
added JUnit test for FixedDuration

### PR DESCRIPTION
**Pull request by Dou-Maokang**

### CODE REVIEW

**Comment by maxxyx96** [comment]
Looks good, waiting for others' inputs before merging PR.

**Comment by e0318465** [comment]
Looks good too, Ting Wei and Gervaise, what do your think?

**Comment by talesrune** [comment]
Looks good too, Gervaise, what do your think?

**Comment by gervaiseang** [comment]
Looks good too, let's proceed to merge PR.

**Pull request merged**
