### PR TITLE
To remove unused code

### PR DESCRIPTION
**Pull request by gervaiseang**

### CODE REVIEW

**Comment by e0318465** [comment]
Opps, did we just pr at the same time

**Comment by gervaiseang** [comment]
Please DO NOT merge this pull request first. Testing integration of Codacy on this PR.

**Comment by e0318465** [comment]
Alright, I merged mine first. Thanks for letting me know!

**Comment by talesrune** [comment]
Hello

**Comment by maxxyx96** [comment]
Jiayous

**Pull request merged**
